workflows:
  build:
    name: Build APK
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Build
        script: |
          flutter create --org com.xray.vpn --project-name vpn .
          cd vpn
          flutter build apk --release
          cd ..
          cp vpn/build/app/outputs/flutter-apk/app-release.apk .
    artifacts:
      - "*.apk"
